### ISSUE TITLE
Method Illuminate\Validation\Validator::validateCountry does not exist.

### ISSUE THREAD

**Issue by xyrintech** [rinvex/laravel-tenants#19]
Method Illuminate\Validation\Validator::validateCountry does not exist.

**Comment by xyrintech** [comment]
Laravel 5.6

**Comment by noxify** [comment]
I assume you're using the `dev-develop` branch.

It seems that the removed dependency to the country package ( https://github.com/rinvex/tenants/commit/203940fe13b39ea08f204787952d3213abbfd6df ) occurs the problem.

Workaround: 
add the rinvex/country package to your `composer.json`

```
composer require rinvex/country:dev-develop
```

---- 

Alternative 1: We have to remove the country validation
https://github.com/rinvex/tenants/blob/7fd89de750e2d78ba2d8c3eda36060167613d478/src/Models/Tenant.php#L170

Alternative 2: We have to add the dependency again.

**Comment by Omranic** [comment]
Thank you for the report, this has been fixed by re-adding the missing dependencies again https://github.com/rinvex/laravel-tenants/commit/8bc5e520260faff356546f6eb2fb1c742e85eaa3
