### ISSUE TITLE
Deprecated or not?

### ISSUE THREAD

**Issue by antonioribeiro** [rinvex/laravel-tenants#22]
It's not the first package I see from Rinvex with this today:

![image](https://user-images.githubusercontent.com/3182864/46389315-7d5ec100-c6a7-11e8-906b-2c4e91a83c29.png)

But it is pointing to itself, so it's abandoned or not?

**Comment by Omranic** [comment]
Not deprecated, sorry for not updating packages sooner, hopefully today with support for Laravel v5.7 and tagging stable release..
