### ISSUE TITLE
Unable to install on laravel 7 and php 7.3

### ISSUE THREAD

**Issue by fahmifitu** [rinvex/laravel-tenants#29]
I set up a new project and was unable to install the package. here's what I'm getting

`composer require rinvex/laravel-tenants
Using version ^3.0 for rinvex/laravel-tenants
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v7.0.0
    - Conclusion: don't install laravel/framework v7.0.0
    - rinvex/laravel-tenants v3.0.0 requires illuminate/database ^6.0.0 -> satisfiable by illuminate/database[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - rinvex/laravel-tenants v3.0.1 requires illuminate/database ^6.0.0 -> satisfiable by illuminate/database[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - rinvex/laravel-tenants v3.0.2 requires illuminate/database ^6.0.0 -> satisfiable by illuminate/database[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - rinvex/laravel-tenants v3.0.3 requires illuminate/database ^6.0.0 -> satisfiable by illuminate/database[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - don't install illuminate/database 6.x-dev|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.0.0|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.0.1|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.0.2|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.0.3|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.0.4|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.1.0|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.10.0|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.11.0|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.12.0|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.13.0|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.13.1|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.14.0|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.15.0|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.15.1|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.16.0|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.17.0|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.17.1|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.18.0|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.18.1|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.18.2|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.18.3|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.18.4|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.18.5|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.18.6|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.2.0|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.3.0|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.4.1|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.5.0|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.5.1|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.5.2|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.6.0|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.6.1|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.6.2|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.7.0|don't install laravel/framework v7.0.0
    - don't install illuminate/database v6.8.0|don't install laravel/framework v7.0.0
    - Installation request for laravel/framework 7.0 -> satisfiable by laravel/framework[v7.0.0].
    - Installation request for rinvex/laravel-tenants ^3.0 -> satisfiable by rinvex/laravel-tenants[v3.0.0, v3.0.1, v3.0.2, v3.0.3].

Installation failed, reverting ./composer.json to its original content.`

**Comment by Omranic** [comment]
Recent release v4.x supports Laravel v7.x but requires PHP v7.4 as a minimum.
If you can't afford PHP v7.4 for now, then feel free to fork this package and lower the minimum required version until you upgrade. I hope this helps :) Happy coding..
